# Generated by Django 3.2.16 on 2023-11-08 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='///', regex='^[\\w.@+-]+$')], verbose_name='Юзернейм'),
        ),
    ]
